name: push to live repo
'on':
  push:
    branches:
      - master
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
        ref: 'master'
    - run: |
        git remote add live https://${{ secrets.GH_USERNAME }}:${{ secrets.GH_PW }}@github.com/texas-HACS/test-repo.git
        git push live master:dev